USE QLNHAKHOA
GO
CREATE PROC Sp_NV_THEMTHUOCVAOHOSO @MANHASI VARCHAR(10), @MATHUOC VARCHAR(10), @SOLUONGCAP INT, @IDHOSOBA VARCHAR(10)
AS
BEGIN TRAN
	BEGIN TRY
		IF NOT EXISTS (SELECT *
		FROM HOSOBENHAN
		WHERE IDHOSOBA = @IDHOSOBA)
		BEGIN
			PRINT CAST (@IDHOSOBA AS VARCHAR(15)) + N' Không Tồn Tại'
			ROLLBACK TRAN
			RETURN 1
		END
		IF @SOLUONGCAP = 0
		BEGIN
			PRINT N'Số lượng câp Phải Khác Không'
			ROLLBACK TRAN
			RETURN 1
		END

		IF NOT EXISTS (SELECT *
		FROM THUOC
		WHERE MATHUOC = @MATHUOC)
		BEGIN
			PRINT CAST (@MATHUOC AS VARCHAR(15)) + N' Không Tồn Tại'
			ROLLBACK TRAN
			RETURN 1
		END

		DECLARE @SLTON INT
		SET @SLTON = 0
		SET @SLTON = (SELECT T.SLTON FROM THUOC T WHERE T.MATHUOC = @MATHUOC)
		IF @SOLUONGCAP > @SLTON
		BEGIN
			PRINT N'Số lượng cấp vượt quá số lượng tồn của thuốc'
			ROLLBACK TRAN
			RETURN 1
		END
		WAITFOR DELAY '00:00:5'

		SET @SLTON = @SLTON - @SOLUONGCAP
		UPDATE THUOC
		SET SLTON = @SLTON
		WHERE MATHUOC = @MATHUOC

		INSERT INTO dbo.CT_THUOC
		(
		    MATHUOC,
		    IDHOSOBA,
		    SOLUONG
		)
		VALUES
		(   @MATHUOC,  -- MATHUOC - varchar(10)
		    @IDHOSOBA,  -- IDHOSOBA - varchar(10)
		    @SOLUONGCAP -- SOLUONG - int
		    )

	END TRY
	BEGIN CATCH
		PRINT N'LỖI HỆ THỐNG'		ROLLBACK TRAN		RETURN 1	
	END CATCH
COMMIT TRAN
RETURN 0